# Generated by Django 2.2.21 on 2022-02-01 13:45

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feeder_gis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=256)),
                ('line', djgeojson.fields.LineStringField(blank=True, null=True)),
                ('load', djgeojson.fields.PointField()),
                ('sub', djgeojson.fields.PolygonField(blank=True, null=True)),
            ],
        ),
    ]
