# Generated by Django 2.2.21 on 2022-02-02 10:52

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20220201_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('geom', djgeojson.fields.PointField(blank=True, null=True)),
                ('poly', djgeojson.fields.PolygonField(blank=True, null=True)),
                ('line', djgeojson.fields.LineStringField(blank=True, null=True)),
            ],
        ),
    ]
