# Generated by Django 2.2.21 on 2022-02-02 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_mushroomspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder_gis',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
