# Generated by Django 2.2.21 on 2022-02-02 11:53

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_feeder_gis_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='cable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.IntegerField()),
                ('feeder', models.IntegerField()),
                ('geom', djgeojson.fields.LineStringField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.IntegerField()),
                ('feeder', models.IntegerField()),
                ('geom', djgeojson.fields.PointField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pillar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.IntegerField()),
                ('feeder', models.IntegerField()),
                ('geom', djgeojson.fields.PolygonField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.IntegerField()),
                ('geom', djgeojson.fields.PolygonField(blank=True, null=True)),
            ],
        ),
    ]
