# Generated by Django 2.2.21 on 2022-02-02 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_cable_load_pillar_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='feeder',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
