# Generated by Django 2.2.21 on 2022-02-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_sub_feeder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sub',
        ),
    ]
