# Generated by Django 2.2.21 on 2022-02-02 12:01

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_delete_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.IntegerField()),
                ('feeder', models.IntegerField()),
                ('geom', djgeojson.fields.PolygonField(blank=True, null=True)),
            ],
        ),
    ]
