# Generated by Django 2.2.21 on 2022-02-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_sub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feeder_gis',
        ),
        migrations.DeleteModel(
            name='MushroomSpot',
        ),
    ]
